### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by eziochiu** [mistydemeo/pgm2xm#2]
```
❯ ./pgm2xm -b z80prg.bin m0600.u5 00 0.xm
BIOS enabled

pgm_m01s.rom loaded at 000000
m0600.u5 loaded at 400000
Song 00 / 04
Header at 8000
Reading file header
[1]    10413 segmentation fault  ./pgm2xm -b z80prg.bin m0600.u5 00 0.xm
```
why?

**Comment by mistydemeo** [comment]
How'd you dump your `z80prg.bin`? Can you email me a copy to test with?

**Comment by mistydemeo** [comment]
Oh, and what game is this from?

**Comment by eziochiu** [comment]
the game name is kovytzy

**Comment by eziochiu** [comment]
Did you receive my email？

**Comment by eziochiu** [comment]
> Oh, and what game is this from?

the game name is kovytzy

**Comment by eziochiu** [comment]
> Oh, and what game is this from?

en，I mean the game name is Knights of Valour: Yi Tong Zhong Yuan, rom zip name is kovytzy.zip

**Comment by mistydemeo** [comment]
I received your email! I'll test soon.

I think the problem may be that the original KoV uses a different driver, and isn't compatible with this tool. However, it would be better if the tool could say that instead of crashing.

**Comment by eziochiu** [comment]
> I received your email! I'll test soon.
> 
> I think the problem may be that the original KoV uses a different driver, and isn't compatible with this tool. However, it would be better if the tool could say that instead of crashing.

I think you are right, according to my experience, Kov's music samples are in the PROM file, not in the M0600 file

**Comment by eziochiu** [comment]
> I received your email! I'll test soon.
> 
> I think the problem may be that the original KoV uses a different driver, and isn't compatible with this tool. However, it would be better if the tool could say that instead of crashing.

The Kov series is special in that there are only sounds samples in the M0600 file, not samples of music
